Zloy-Postgres:
  restart: always
  image: sameersbn/postgresql:9.6-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - PG_PASSWORD=passw0rd
    - DB_USER=zloy
    - DB_PASS=zloy
    - DB_NAME=db_shop
    - DB_EXTENSION=pgcrypto
